export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const GET_GENDERS = 'GET_GENDERS';
export const GET_GENDERS_SUCCESS = 'GET_GENDERS_SUCCESS';